// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::A5:
			return "Cam input (PA5)";
		case Gpio::A8:
			return "PA8 Ignition 3";
		case Gpio::B13:
			return "PB13 Ignition 1";
		case Gpio::B14:
			return "PB14 Injector 6";
		case Gpio::B15:
			return "PB15 Stepper Step";
		case Gpio::B7:
			return "Launch Control input (PB7)";
		case Gpio::B9:
			return "PB9 Injector 3";
		case Gpio::C13:
			return "PC13 Injector 8";
		case Gpio::C6:
			return "Crank input (PC6)";
		case Gpio::C7:
			return "VSS HALL input (PC7)";
		case Gpio::C8:
			return "PC8 Going low (Idle 2)";
		case Gpio::C9:
			return "PC9 Going Low output (low current)";
		case Gpio::D10:
			return "PD10 Ignition 7";
		case Gpio::D11:
			return "PD11 Ignition 6";
		case Gpio::D3:
			return "PD3 Ignition 5";
		case Gpio::D4:
			return "PD4 Going low (boost)";
		case Gpio::D5:
			return "PD5 Going High output";
		case Gpio::D6:
			return "PD6 Going low (Idle 1)";
		case Gpio::D7:
			return "PD7 Going low (VVT)";
		case Gpio::D8:
			return "PD8 Ignition 8";
		case Gpio::D9:
			return "PD9 Injector 5";
		case Gpio::E10:
			return "PE10 Tach Output";
		case Gpio::E12:
			return "Flex fuel input (PE12)";
		case Gpio::E13:
			return "PE13 Stepper Direction";
		case Gpio::E14:
			return "PE14 Injector 7";
		case Gpio::E15:
			return "PE15 Stepper Enable";
		case Gpio::E3:
			return "PE3 Injector 4";
		case Gpio::E4:
			return "PE4 Ignition 4";
		case Gpio::E5:
			return "PE5 Injector 2";
		case Gpio::E6:
			return "PE6 Injector 1";
		case Gpio::E7:
			return "PE7 Fan 1";
		case Gpio::E8:
			return "PE8 Fuel Pump";
		case Gpio::E9:
			return "PE9 Ignition 2";
		default:
			return nullptr;
	}
	return nullptr;
}
